# Generated by Django 5.2.1 on 2025-05-10 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=63, verbose_name='Título')),
                ('area', models.CharField(choices=[('Ti', 'Tecnologia da Informação'), ('Rh', 'Recursos Humanos'), ('Fi', 'Financeiro'), ('Tr', 'Transporte')], max_length=2, verbose_name='Área')),
                ('tipo_contrato', models.CharField(max_length=2, verbose_name='Tipo de contrato')),
                ('descricao', models.TextField(max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=31, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=31, verbose_name='Sobrenome')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('genero', models.CharField(choices=[('Ma', 'Masculino'), ('Fe', 'Feminino'), ('Nb', 'Não Binário'), ('Ou', 'Outros')], max_length=2, verbose_name='Gênero')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=10, verbose_name='Telefone')),
                ('escolaridade', models.CharField(choices=[('FUN', 'Fundamental'), ('MED', 'Médio'), ('SUP', 'Superior'), ('POS', 'Pós-graduação'), ('MES', 'Mestrado'), ('DOU', 'Doutorado')], max_length=63, verbose_name='Escolaridade')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaga_candidato.vaga')),
            ],
        ),
    ]
