# Generated by Django 5.2.1 on 2025-05-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga_candidato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='tipo_contrato',
            field=models.CharField(choices=[('CLT', 'Consolidação das Leis do Trabalho'), ('PJ', 'Pessoa Jurídica'), ('MEI', 'Microempreendedor'), ('COO', 'Cooperado')], max_length=3, verbose_name='Tipo de contrato'),
        ),
    ]
